version: '3.8'

services:
  php:
    container_name: test_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/memory_limit.ini:/usr/local/etc/php/conf.d/memory_limit.ini
      - .:/var/www/symfony_docker:cached
      - var:/var/www/symfony_docker/var:cached
      - vendor:/var/www/symfony_docker/vendor:cached
    tty: true

  nginx:
    container_name: test_nginx
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - .:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  var:
  vendor:
